In [1]:
import numpy as np
import random
import time

Вправа 1: Введіть число $n$. Виведіть масив розміром $n \times n$, де на головній діагоналі знаходяться числа від 1 до $n$, а всі інші елементи масиву рівні 0.

In [50]:
def task_1_N(n):
    res=np.diag(np.arange(1, n+1))
    return res
n=int(input("n = "))
res=task_1_N(n)
print(res)

n = 6
[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


In [51]:
def task_1_I(n):
    res = []
    for i in range(n):
        st = []
        for j in range(n):
            if i==j:
                st.append(i+1)
            else:
                st.append(0)
        res.append(st)
    return res
n=int(input("n = "))
res=task_1_I(n)
for i in res:
    print(i)


n = 6
[1, 0, 0, 0, 0, 0]
[0, 2, 0, 0, 0, 0]
[0, 0, 3, 0, 0, 0]
[0, 0, 0, 4, 0, 0]
[0, 0, 0, 0, 5, 0]
[0, 0, 0, 0, 0, 6]


Вправа 2:Введіть число $n$. Створіть матрицю розміром $n \times n$ з елементами 1 та 0 у шаховому порядку. Почніть з 1 в лівому верхньому куті матриці і чергуюйте 1 та 0 по рядках і стовпцях.

In [52]:
def task_2_N(n):
    res=np.zeros((n, n),dtype=int)
    res[1::2, ::2] = 1
    res[::2, 1::2] = 1
    return res
n=int(input("n = "))
res=task_2_N(n)
print(res)

n = 6
[[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]


In [53]:
def task_2_I(n):
    res = []
    for i in range(n):
        st = []
        for j in range(n):
            st.append(0)
        res.append(st)
    for i in range(n):
        for j in range(n):
            if (i + j) % 2 == 1:
                res[i][j] = 1
    return res
n=int(input("n = "))
res=task_2_I(n)
for i in res:
    print(i)

n = 6
[0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0]


Вправа 4: Введіть числа $n$ та $m$. Створіть матрицю розміром $n \times m$. Перший рядок матриці (рядок з нульовим індексом) повинен містити числа від 0 до $m-1$, а всі інші елементи матриці повинні бути рівні 0.

In [54]:
def task_4_N(n,m):
    res=np.zeros((n, m),dtype=int)
    res[0, :] = np.arange(m)
    return res
n=int(input("n = "))
m=int(input("m = "))
res=task_4_N(n,m)
print(res)

n = 6
m = 3
[[0 1 2]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [55]:
def task_4_I(n,m):
    res = []
    for i in range(n):
        st = []
        for j in range(m):
            st.append(0)
        res.append(st)
    for j in range(m):
        res[0][j] = j
    return res
n=int(input("n = "))
m=int(input("m = "))
res=task_4_I(n,m)
for i in res:
    print(i)

n = 6
m = 3
[0, 1, 2]
[0, 0, 0]
[0, 0, 0]
[0, 0, 0]
[0, 0, 0]
[0, 0, 0]


Вправа 7: Введіть масив. Замініть всі нульові елементи введеного масиву на -1.

In [56]:
def task_7_N(res):
    res[res == 0] = -1
    return res
res=np.array(input().split(), dtype=int)
res=task_7_N(res)
print(res)

4 7 0 8 0 9 0 3 0
[ 4  7 -1  8 -1  9 -1  3 -1]


In [57]:
def task_7_I(res):
    for i in range(len(res)):
        if res[i] == 0:
            res[i] = -1
    return res

res=list(map(int,input().split())) 
res=task_7_I(res)
print(res)

3 4 7 0 9 0 8 0 8
[3, 4, 7, -1, 9, -1, 8, -1, 8]


Вправа 8: З клавіатури вводиться масив. Підрахувати в ньому кількість
нульових та ненульвих елементів.

In [58]:
def task_8_N(res):
    nonzero=np.count_nonzero(res)
    print("Не нулі: ")
    print(nonzero)
    zero=len(res)-nonzero
    print("Нулі: ")
    print(zero)
res=np.array(input().split(), dtype=int)
task_8_N(res)

3 4 7 0 9 0 8 0 8
Не нулі: 
6
Нулі: 
3


In [59]:
def task_8_I(res):
    k=0
    for i in res:
        if i == 0:
            k=k+1
    l=len(res)-k        
    print("Не нулі: ")
    print(l)    
    print("Нулі: ")
    print(k)

res=list(map(int,input().split())) 
task_8_I(res)

3 4 7 0 9 0 8 0 8
Не нулі: 
6
Нулі: 
3


Вправа 12: Створіть масив розміром $n \times n$, де всі елементи дорівнюють 1. Створіть "рамку" з 0, оточуючу всі 1 всередині масиву.

In [60]:
def task_12_N(n):
    res=np.ones((n, n))
    res[0, :] = 0
    res[-1, :] = 0
    res[:, 0] = 0
    res[:, -1] = 0
    return res
n=int(input("n = "))
res=task_12_N(n)
print(res)

n = 7
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [61]:
def task_12_I(n):
    res = []
    for i in range(n):
        st = []
        for j in range(n):
            st.append(1.)
        res.append(st)
    for i in range(n):
        for j in range(n):
            if i == 0 or i == n - 1 or j == 0 or j == n - 1:
                res[i][j] = 0.
    return res
n=int(input("n = "))
res=task_12_I(n)
for i in res:
    print(i)

n = 7
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0]
[0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0]
[0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0]
[0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0]
[0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]


Вправа 15: Створіть матрицю розміром $n \times n$, де парні стовбці містять одиниці, а непарні стовбці містять нулі.

In [62]:
def task_15_N(n):
    res=np.zeros((n,n),dtype=int)
    res[:, 1::2] = 1
    return res
n=int(input("n = "))
res=task_15_N(n)
print(res)

n = 7
[[0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0]]


In [63]:
def task_15_I(n):
    res = []
    for i in range(n):
        st = []
        for j in range(n):
            st.append(0)
        res.append(st)
    for i in range(n):
        for j in range(n):
            if j%2!=0:
                res[i][j]=1
    return res
n=int(input("n = "))
res=task_15_I(n)
for i in res:
    print(i)

n = 7
[0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0]


Вправа 16: Створіть вектор, який містить значення від 0 до $n$. Замініть всі значення, які більші за $\frac{n}{4}$ та менші за $\frac{3n}{4}$, на нулі.

In [64]:
def task_16_N(n):
    res=np.arange(n)
    res[(res > n/4) & (res < 3*n/4)] = 0
    return res
n=int(input("n = "))
res=task_16_N(n)
print(res)

n = 8
[0 1 2 0 0 0 6 7]


In [65]:
def task_16_I(n):
    res = []
    for i in range(n):
        number=random.randint(0, n-1)
        res.append(number)
    for i in range(n):
        if res[i]>n/2 and res[i]<3*n/4:
            res[i]==0
    return res

n=int(input("n = "))
res=task_16_I(n)
print(res)

n = 8
[2, 0, 0, 3, 2, 0, 0, 1]


Вправа 20: Згенеруйте вектор, який містить $n$ випадкових елементів, які належать інтервалу (0, 1). Замініть максимальний елемент вектора на 0.

In [66]:
def task_20_N(res):
    res[np.argmax(res)] = 0
    return res
n=int(input("n = "))
res=np.random.rand(n)
print(res)
res=task_20_N(res)
print(res)

n = 5
[0.21672365 0.45097476 0.15956977 0.67941418 0.79679573]
[0.21672365 0.45097476 0.15956977 0.67941418 0.        ]


In [67]:
def task_20_I(n):
    res = []
    k=0
    for i in range(n):
        number=random.random()
        res.append(number)
    print(res)
    m=max(res)
    for i in range(n):
        if res[i]==m:
            k=i
    res[k]=0
    return res

n=int(input("n = "))
res=task_20_I(n)
print(res)

n = 5
[0.3511534021949059, 0.6945461619027307, 0.9579299199590653, 0.4766066423824028, 0.5982223592737644]
[0.3511534021949059, 0.6945461619027307, 0, 0.4766066423824028, 0.5982223592737644]


In [69]:
print("Вправа 1:")
%timeit -n 100 -r 10 task_1_N
%timeit -n 100 -r 10 task_1_I
print("Вправа 2:")
%timeit -n 100 -r 10 task_2_N
%timeit -n 100 -r 10 task_2_I
print("Вправа 4:")
%timeit -n 100 -r 10 task_4_N
%timeit -n 100 -r 10 task_4_I
print("Вправа 7:")
%timeit -n 100 -r 10 task_7_N
%timeit -n 100 -r 10 task_7_I
print("Вправа 8:")
%timeit -n 100 -r 10 task_8_N
%timeit -n 100 -r 10 task_8_I
print("Вправа 12:")
%timeit -n 100 -r 10 task_12_N
%timeit -n 100 -r 10 task_12_I
print("Вправа 15:")
%timeit -n 100 -r 10 task_15_N
%timeit -n 100 -r 10 task_15_I
print("Вправа 16:")
%timeit -n 100 -r 10 task_16_N
%timeit -n 100 -r 10 task_16_I
print("Вправа 20:")
%timeit -n 100 -r 10 task_20_N
%timeit -n 100 -r 10 task_20_I

Вправа 1:
18.3 ns ± 4 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)
18.3 ns ± 2.93 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)
Вправа 2:
19.8 ns ± 4.42 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)
19.8 ns ± 3.79 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)
Вправа 4:
19.4 ns ± 3.56 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)
19.5 ns ± 3.23 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)
Вправа 7:
78.2 ns ± 7.49 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)
35.7 ns ± 16.3 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)
Вправа 8:
36.2 ns ± 5.02 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)
34.7 ns ± 47.9 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)
Вправа 12:
18.3 ns ± 3.58 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)
18.3 ns ± 3.26 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)
Вправа 15:
28.8 ns ± 5.17 ns per loop (mean ± std. dev. of 10 runs

Розв'яжіть систему рівнянь за допомогою методу Крамера та виконайте перевірку рішення за допомогою наступних методів:
a) Матричного множення;
b) Використання оберненої матриці;
c) Використання функції numpy.linalg.solve().

Порівняйте всі рішення за допомогою функції numpy.allclose() для визначення близькості результатів.

\begin{cases}
x_1 + 2x_2 + x_3 + x_4 &= 8 \\
2x_1 + x_2 + x_3 + x_4 &= 5 \\
x_1 - x_2 + 2x_3 + x_4 &= -1 \\
x_1 + x_2 - x_3 + 3x_4 &= 10
\end{cases}

In [22]:
A = np.array([[1, 2, 1, 1], [2, 1, 1, 1], [1, -1, 2, 1], [1, 1, -1, 3]])
B = np.array([8, 5, -1, 10])
detA=np.linalg.det(A)
A1 = A.copy()
A1[:, 0] = B
detA1 = np.linalg.det(A1)
A2 = A.copy()
A2[:, 1] = B
detA2 = np.linalg.det(A2)
A3 = A.copy()
A3[:, 2] = B
detA3 = np.linalg.det(A3)
A4 = A.copy()
A4[:, 3] = B
detA4 = np.linalg.det(A4)
X=[detA1 / detA,detA2 / detA,detA3 / detA,detA4 / detA]
print(X)

[-0.05263157894736862, 2.9473684210526305, -0.1578947368421053, 2.3157894736842115]


In [23]:
res1 = np.dot(np.linalg.inv(A), B)
print(res1)

[-0.05263158  2.94736842 -0.15789474  2.31578947]


In [24]:
res2 = np.dot(A,X)
print(res2)

[ 8.  5. -1. 10.]


In [26]:
res3 = np.linalg.solve(A, B)
print(res3)

[-0.05263158  2.94736842 -0.15789474  2.31578947]


In [27]:
first=np.allclose(X,res1)
if first:
    print("а)Результат однаковий")
else:
     print("а)Результат різний")
second=np.allclose(B,res2)
if second:
    print("b)Результат однаковий")
else:
     print("b)Результат різний")
third=np.allclose(X,res3)
if third:
    print("c)Результат однаковий")
else:
     print("c)Результат різний")

а)Результат однаковий
b)Результат однаковий
c)Результат однаковий


Обчислити значення матричного виразу:
а) з використанням універсальних функцій бібліотеки NumPy.
b) за допомогою ітеративних конструкцій (з використанням циклів,
спискових включень тощо).
с) для обох випадків підрахувати час виконання скрипту та зробити
висновок.
Порівняти всі рішення за допомогою функції numpy.allclose()

\begin{align*}
2A - (A^2+B)B, \text{де } А &= \begin{pmatrix}
1 & 4 & 2 \\
2 & 1 & 2 \\
0 & 1 & 1
\end{pmatrix}
,B&= 
\begin{pmatrix}
4 & 6 & 2 \\
4 & 10 & 1 \\
2 & 4 & 5
\end{pmatrix}
\end{align*}

In [44]:
%%timeit -n 100 -r 10
A = np.array([[1, 4, 2], [2, 1, 2], [0, 1, 1]])
B = np.array([[4, 6, 2], [4, 10, 1], [2, 4, 5]])
result=2*A-(np.dot(A, A)+B)*B


23 µs ± 7.28 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


In [43]:
print(result)

[[ -50  -88  -24]
 [ -28 -208   -5]
 [  -8  -22  -38]]


In [48]:
%%timeit -n 100 -r 10
A = np.array([[1, 4, 2], [2, 1, 2], [0, 1, 1]])
B = np.array([[4, 6, 2], [4, 10, 1], [2, 4, 5]])
n=3
res2 = [[0, 0, 0],[0, 0, 0],[0, 0, 0]]
sq = [[0, 0, 0],[0, 0, 0],[0, 0, 0]]
for i in range(n):
    for j in range(n):
        for k in range(n):
            sq[i][j] += A[i][k] * A[k][j]

for i in range(n):
    for j in range(n):
        res2[i][j] = 2 * A[i][j] - (sq[i][j] + B[i][j]) * B[i][j]


61.9 µs ± 22.6 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


In [47]:
for i in res2:
    print(i)

[-50, -88, -24]
[-28, -208, -5]
[-8, -22, -38]


In [49]:
first=np.allclose(result,res2)
if first:
    print("Результат однаковий")
else:
     print("Результат різний")


Результат однаковий
